### ISSUE TITLE
Incompatibility issue with Rustic

### ISSUE THREAD

**Issue by MishkaG** [BuiltBrokenModding/ICBM-Classic#184]
Cast exception seems to have been introduced at build 3.3.0b58 - although the below report was produced with the latest build of both mods and forge.

[crash report](https://pastebin.com/UQ8RczfG)

**Comment by DarkGuardsman** [comment]
Not an issue with Rustic, I forgot to change the reference out when we went from using the MC model to our own model. Seems that method I fixed is not normally used in the game. So my guess is that Rustic triggers it but I have no clue what the mod does so can't say why. However, what I can say is that this would have crash for anything calling that method.

**Comment by Deloyar81** [comment]
Wizardry triggers it too - any suggestions rather than a rollback to 3.3.0b57?

**Comment by DarkGuardsman** [comment]
Should be fixed the latest?

**Comment by Deloyar81** [comment]
I'm sorry, it's still crashing - with the latest updates .

[Pastebin Crashlog](https://pastebin.com/u4bwequw)

Forge 14.23.5.2807
ICBM - Classic 3.3.0b60
Rustic 1.0.15
Wizardry 0.9.9

**Comment by MishkaG** [comment]
I'm using ICBM 3.3.0b61 and it's working fine.

**Comment by MishkaG** [comment]
Seems the issue is that 3.3.0b61 isn't currently on Curse.

**Comment by Deloyar81** [comment]
Neither on Curse nor the twitch launcher has 3.3.0b61. ;)

**Comment by MishkaG** [comment]
I see that - it was there ~8 days ago.

**Comment by DarkGuardsman** [comment]
ya 61 was removed due to a different crash caused by early rewrite code getting pushed. Looks like I need to push another build out if this is still a problem.

**Comment by MishkaG** [comment]
It is a problem in 3.3.0b60 for sure, it's where I generated my first error log - introduced at 3.3.0b58.

**Comment by DarkGuardsman** [comment]
Build 62 should be released soon with the fix for issues in build 60 and issues in build 58
